services:
  - type: web
    name: foster-care-displacement-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y openjdk-11-jdk
      pip install -r requirements.txt
    startCommand: streamlit run foster-care-displacement-pred.py
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-11-openjdk-amd64
